export type TitleType = 'movie' | 'tv' | 'anime';
export type UserStatus = 'watchlist' | 'watching' | 'watched';
export type ProviderKind = 'streaming' | 'free' | 'rent' | 'buy' | 'info';

export type Provider = { name: string; kind: ProviderKind; url?: string; logo?: string };
export type Title = {
  id: string; name: string; type: TitleType; poster: string; backdrop: string;
  description: string; releaseYear: number; genres: string[]; rating: number;
  runtime: string; cast: string[]; director: string; seasons?: number; episodes?: number;
  providers: Provider[];
};
export type UserTitle = {
  titleId: string; status: UserStatus; dateAdded: string; dateWatched?: string;
  rating?: number; review?: string; currentSeason?: number; currentEpisode?: number; progress?: number;
};
export type Profile = { username: string; country: string; appearance: 'night' | 'day'; };

const escapeSvgText = (value: string) => value.replace(/[<>&'"]/g, (character) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '\'': '&apos;', '"': '&quot;' })[character] ?? character);
export const coverArt = (label: string, type: TitleType) => {
  const palette = type === 'movie' ? ['#5b263e', '#e47a58'] : type === 'tv' ? ['#163e49', '#76b7a6'] : ['#5e3b26', '#d5af71'];
  const safeLabel = escapeSvgText(label.slice(0, 28));
  return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 780 1100"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${palette[0]}"/><stop offset="1" stop-color="#15182a"/></linearGradient></defs><rect width="780" height="1100" fill="url(#g)"/><circle cx="640" cy="170" r="180" fill="${palette[1]}" opacity=".22"/><path d="M0 920C220 760 420 1010 780 820V1100H0Z" fill="#0d101b" opacity=".72"/><text x="58" y="925" fill="#f2e9d9" font-family="Georgia,serif" font-size="54">${safeLabel}</text><text x="60" y="982" fill="${palette[1]}" font-family="monospace" font-size="18" letter-spacing="4">DUCERE CATALOG</text></svg>`)}`;
};
const posterUrl = (path: string) => path.startsWith('http') ? path : `https://image.tmdb.org/t/p/w500${path}`;
const backdropUrl = (path: string) => path.startsWith('http') ? path : `https://image.tmdb.org/t/p/w1280${path}`;
const img = (path: string) => posterUrl(path);
const back = (path: string) => backdropUrl(path);

const curatedTitle = (
  id: string,
  name: string,
  type: TitleType,
  posterPath: string,
  releaseYear: number,
  genres: string[],
  rating: number,
  description: string,
  runtime: string,
  cast: string[],
  director: string,
  providers: Provider[],
  series?: { seasons: number; episodes: number },
): Title => ({
  id,
  name,
  type,
  poster: posterUrl(posterPath),
  backdrop: posterUrl(posterPath),
  releaseYear,
  genres,
  rating,
  description,
  runtime,
  cast,
  director,
  providers,
  ...(series ?? {}),
});

const EXPANDED_TITLES: Title[] = [
  curatedTitle('parasite', 'Parasite', 'movie', '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 2019, ['Thriller', 'Drama', 'Comedy'], 8.5, 'A struggling family slowly insinuates itself into the home of a wealthy household, with consequences that blur every line of class and trust.', '2h 12m', ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'], 'Bong Joon-ho', [{ name: 'Prime Video', kind: 'rent' }, { name: 'Apple TV', kind: 'buy' }]),
  curatedTitle('the-godfather', 'The Godfather', 'movie', '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 1972, ['Crime', 'Drama'], 9.2, 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', '2h 55m', ['Marlon Brando', 'Al Pacino', 'James Caan'], 'Francis Ford Coppola', [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('pulp-fiction', 'Pulp Fiction', 'movie', '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', 1994, ['Crime', 'Drama', 'Thriller'], 8.9, 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', '2h 34m', ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'], 'Quentin Tarantino', [{ name: 'Prime Video', kind: 'rent' }, { name: 'Apple TV', kind: 'buy' }]),
  curatedTitle('the-matrix', 'The Matrix', 'movie', '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 1999, ['Action', 'Sci-Fi', 'Thriller'], 8.7, 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', '2h 16m', ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'], 'The Wachowskis', [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('lotr-fellowship', 'The Lord of the Rings: The Fellowship of the Ring', 'movie', '/6oom5QYQ2yQTMJIbnvbkblGvXc.jpg', 2001, ['Fantasy', 'Adventure', 'Drama'], 8.9, 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.', '2h 58m', ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'], 'Peter Jackson', [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('arrival', 'Arrival', 'movie', '/x2FJsf1ElAgr63Y0i3D9w1f3L8.jpg', 2016, ['Sci-Fi', 'Drama', 'Mystery'], 7.9, 'A linguist works with the military to communicate with alien lifeforms after mysterious spacecraft appear around the world.', '1h 56m', ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'], 'Denis Villeneuve', [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Apple TV', kind: 'rent' }]),
  curatedTitle('dune', 'Dune', 'movie', '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 2021, ['Sci-Fi', 'Adventure', 'Drama'], 8.0, 'A gifted young man must travel to the most dangerous planet in the universe to ensure the future of his family and his people.', '2h 35m', ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac'], 'Denis Villeneuve', [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('oppenheimer', 'Oppenheimer', 'movie', '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 2023, ['Drama', 'History', 'Thriller'], 8.1, 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', '3h 0m', ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'], 'Christopher Nolan', [{ name: 'Peacock', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('barbie', 'Barbie', 'movie', '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg', 2023, ['Comedy', 'Fantasy', 'Adventure'], 6.8, 'Barbie suffers a crisis that leads her to leave the perfection of Barbieland for the real world.', '1h 54m', ['Margot Robbie', 'Ryan Gosling', 'America Ferrera'], 'Greta Gerwig', [{ name: 'Max', kind: 'streaming' }, { name: 'Apple TV', kind: 'rent' }]),
  curatedTitle('top-gun-maverick', 'Top Gun: Maverick', 'movie', '/62HCnUTziyWcpDaBO2i1DX17ljL.jpg', 2022, ['Action', 'Drama'], 8.2, 'After more than thirty years of service as one of the Navy’s top aviators, Pete Maverick Mitchell trains a new squadron for a dangerous mission.', '2h 11m', ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'], 'Joseph Kosinski', [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('everything-everywhere', 'Everything Everywhere All at Once', 'movie', '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg', 2022, ['Action', 'Comedy', 'Sci-Fi'], 7.8, 'An exhausted laundromat owner is swept into an insane multiverse adventure where she alone can save existence.', '2h 19m', ['Michelle Yeoh', 'Ke Huy Quan', 'Jamie Lee Curtis'], 'Daniel Kwan & Daniel Scheinert', [{ name: 'Prime Video', kind: 'rent' }, { name: 'Apple TV', kind: 'buy' }]),
  curatedTitle('get-out', 'Get Out', 'movie', '/tFXcEccSQMf3dQZ00jjJz8fJ3Qf.jpg', 2017, ['Horror', 'Mystery', 'Thriller'], 7.7, 'A young Black man visits his white girlfriend’s family estate and discovers a sinister secret beneath their polite welcome.', '1h 44m', ['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'], 'Jordan Peele', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('spirited-away', 'Spirited Away', 'movie', '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 2001, ['Animation', 'Fantasy', 'Adventure'], 8.6, 'A young girl enters a world ruled by gods, witches, and spirits where humans are changed into beasts.', '2h 5m', ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'], 'Hayao Miyazaki', [{ name: 'Max', kind: 'streaming' }, { name: 'Apple TV', kind: 'rent' }]),
  curatedTitle('whiplash', 'Whiplash', 'movie', '/7fn624j5lj3hTwuJvI4M4s8O9LQ.jpg', 2014, ['Drama', 'Music'], 8.5, 'A promising young drummer enrolls at a cut-throat music conservatory where his teacher will stop at nothing to realize a student’s potential.', '1h 47m', ['Miles Teller', 'J.K. Simmons', 'Paul Reiser'], 'Damien Chazelle', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('better-call-saul', 'Better Call Saul', 'tv', '/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg', 2015, ['Crime', 'Drama'], 8.9, 'The trials and tribulations of criminal lawyer Jimmy McGill before his fateful encounter with Walter White.', '6 seasons', ['Bob Odenkirk', 'Rhea Seehorn', 'Jonathan Banks'], 'Vince Gilligan', [{ name: 'Netflix', kind: 'streaming' }, { name: 'AMC+', kind: 'streaming' }], { seasons: 6, episodes: 63 }),
  curatedTitle('the-office', 'The Office', 'tv', '/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg', 2005, ['Comedy', 'Workplace'], 8.5, 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.', '9 seasons', ['Steve Carell', 'Rainn Wilson', 'John Krasinski'], 'Greg Daniels', [{ name: 'Peacock', kind: 'streaming' }, { name: 'Prime Video', kind: 'buy' }], { seasons: 9, episodes: 201 }),
  curatedTitle('dark', 'Dark', 'tv', '/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg', 2017, ['Mystery', 'Sci-Fi', 'Drama'], 8.7, 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes a mystery spanning generations.', '3 seasons', ['Louis Hofmann', 'Lisa Vicari', 'Maja Schöne'], 'Baran bo Odar', [{ name: 'Netflix', kind: 'streaming' }], { seasons: 3, episodes: 26 }),
  curatedTitle('succession', 'Succession', 'tv', '/7Ru7u0hH7W7J1w4s8Q9Hq7n5J1n.jpg', 2018, ['Drama', 'Comedy'], 8.9, 'The Roy family is known for controlling the biggest media and entertainment company in the world, but their lives change when their father steps back.', '4 seasons', ['Brian Cox', 'Jeremy Strong', 'Sarah Snook'], 'Jesse Armstrong', [{ name: 'Max', kind: 'streaming' }], { seasons: 4, episodes: 39 }),
  curatedTitle('severance', 'Severance', 'tv', '/lR5jfwx6NU04L1bE7x8cD8V1O3U.jpg', 2022, ['Sci-Fi', 'Mystery', 'Drama'], 8.7, 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.', '2 seasons', ['Adam Scott', 'Britt Lower', 'John Turturro'], 'Dan Erickson', [{ name: 'Apple TV+', kind: 'streaming' }], { seasons: 2, episodes: 19 }),
  curatedTitle('the-mandalorian', 'The Mandalorian', 'tv', '/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg', 2019, ['Sci-Fi', 'Adventure', 'Action'], 8.6, 'A lone bounty hunter makes his way through the outer reaches of the galaxy, far from the authority of the New Republic.', '3 seasons', ['Pedro Pascal', 'Carl Weathers', 'Giancarlo Esposito'], 'Jon Favreau', [{ name: 'Disney+', kind: 'streaming' }], { seasons: 3, episodes: 24 }),
  curatedTitle('house-of-the-dragon', 'House of the Dragon', 'tv', '/z2yahl2uefxDla0nf5uyez2uP3h.jpg', 2022, ['Fantasy', 'Drama', 'Action'], 8.4, 'The Targaryen dynasty is at the absolute apex of its power, with more than fifteen dragons under their control.', '2 seasons', ['Emma D’Arcy', 'Matt Smith', 'Olivia Cooke'], 'Ryan Condal', [{ name: 'Max', kind: 'streaming' }], { seasons: 2, episodes: 18 }),
  curatedTitle('arcane', 'Arcane', 'tv', '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg', 2021, ['Animation', 'Fantasy', 'Action'], 9.0, 'Amid the stark discord between twin cities, two sisters fight on rival sides of a war between magic technologies and clashing convictions.', '2 seasons', ['Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro'], 'Christian Linke', [{ name: 'Netflix', kind: 'streaming' }], { seasons: 2, episodes: 18 }),
  curatedTitle('the-queens-gambit', 'The Queen’s Gambit', 'tv', '/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg', 2020, ['Drama'], 8.5, 'An orphaned chess prodigy struggles with addiction in a quest to become the greatest chess player in the world.', '1 season', ['Anya Taylor-Joy', 'Thomas Brodie-Sangster', 'Moses Ingram'], 'Scott Frank', [{ name: 'Netflix', kind: 'streaming' }], { seasons: 1, episodes: 7 }),
  curatedTitle('the-bear', 'The Bear', 'tv', '/sHFlbKS3U7H0uJr6KJ7nJ5c5V0A.jpg', 2022, ['Drama', 'Comedy'], 8.6, 'A young chef from the fine dining world returns to Chicago to run his family’s sandwich shop.', '3 seasons', ['Jeremy Allen White', 'Ayo Edebiri', 'Ebon Moss-Bachrach'], 'Christopher Storer', [{ name: 'Hulu', kind: 'streaming' }, { name: 'Disney+', kind: 'streaming' }], { seasons: 3, episodes: 28 }),
  curatedTitle('true-detective', 'True Detective', 'tv', '/aowDY7cCr4xF6l7aZ8d0K3CqL9p.jpg', 2014, ['Crime', 'Mystery', 'Drama'], 8.9, 'Anthology series in which each season follows a different detective or set of detectives as they investigate a terrible crime.', '4 seasons', ['Matthew McConaughey', 'Woody Harrelson', 'Jodie Foster'], 'Nic Pizzolatto', [{ name: 'Max', kind: 'streaming' }], { seasons: 4, episodes: 30 }),
  curatedTitle('my-hero-academia', 'My Hero Academia', 'anime', '/phM9bb6s9c60dkc6sW0v7dH0t4Y.jpg', 2016, ['Animation', 'Action', 'Fantasy'], 8.0, 'A boy born without superpowers in a world where they are commonplace dreams of becoming a hero himself.', '7 seasons', ['Daiki Yamashita', 'Justin Briner', 'Nobuhiko Okamoto'], 'Kōhei Horikoshi', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }], { seasons: 7, episodes: 159 }),
  curatedTitle('death-note', 'Death Note', 'anime', '/iigTJJskR1PcjjXqxdyJwvbWq5o.jpg', 2006, ['Animation', 'Mystery', 'Thriller'], 8.6, 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a mysterious notebook.', '1 season', ['Mamoru Miyano', 'Kappei Yamaguchi', 'Shidō Nakamura'], 'Tsugumi Ohba', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }], { seasons: 1, episodes: 37 }),
  curatedTitle('fullmetal-alchemist-brotherhood', 'Fullmetal Alchemist: Brotherhood', 'anime', '/5ZFUEOULaV8M2i5i1J6vYfXnY0D.jpg', 2009, ['Animation', 'Action', 'Fantasy'], 9.1, 'Two brothers search for a Philosopher’s Stone after an attempt to use alchemy to revive their dead mother goes awry.', '1 season', ['Romi Park', 'Rie Kugimiya', 'Vic Mignogna'], 'Hiromu Arakawa', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }], { seasons: 1, episodes: 64 }),
  curatedTitle('your-name', 'Your Name.', 'anime', '/q719jXXEzOoYaps6babgKnONONX.jpg', 2016, ['Animation', 'Romance', 'Fantasy'], 8.4, 'Two strangers find themselves mysteriously linked across time and space, waking up in each other’s lives.', '1h 46m', ['Ryunosuke Kamiki', 'Mone Kamishiraishi', 'Masami Nagasawa'], 'Makoto Shinkai', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('weathering-with-you', 'Weathering with You', 'anime', '/qgrk7r1fV4IjuoeiGS5HOhXNdL8.jpg', 2019, ['Animation', 'Romance', 'Fantasy'], 8.0, 'A high-school boy who has run away to Tokyo befriends a girl who appears to have the ability to manipulate the weather.', '1h 52m', ['Daigo Matsuhi', 'Nana Mori', 'Tsubasa Honda'], 'Makoto Shinkai', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Apple TV', kind: 'rent' }]),
  curatedTitle('one-punch-man', 'One-Punch Man', 'anime', '/iM0sM9p0vW8n6t7c2L1q4R5y6U3.jpg', 2015, ['Animation', 'Action', 'Comedy'], 8.4, 'The story of Saitama, a hero who can defeat any opponent with a single punch and is searching for a worthy challenge.', '3 seasons', ['Makoto Furukawa', 'Kaito Ishikawa', 'Max Mittelman'], 'ONE', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }], { seasons: 3, episodes: 36 }),
  curatedTitle('spy-x-family', 'SPY x FAMILY', 'anime', '/3r4LYFuXrg3G8fep7l8Yx8a0u7T.jpg', 2022, ['Animation', 'Comedy', 'Action'], 8.3, 'A spy, an assassin, and a telepath form a fake family to complete a high-stakes mission, each hiding their true identity.', '2 seasons', ['Takuya Eguchi', 'Atsumi Tanezaki', 'Saori Hayami'], 'Tatsuya Endo', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }], { seasons: 2, episodes: 37 }),
  curatedTitle('vinland-saga', 'Vinland Saga', 'anime', '/dJteV6M7q7p1h4r5m8z3c0b2n9x.jpg', 2019, ['Animation', 'Action', 'Drama'], 8.8, 'After his father is killed, a young Viking joins the mercenary band responsible, waiting for the day he can challenge their leader.', '2 seasons', ['Yūto Uemura', 'Shizuka Ishigami', 'Naoya Uchida'], 'Makoto Yukimura', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Crunchyroll', kind: 'streaming' }], { seasons: 2, episodes: 48 }),
  curatedTitle('cowboy-bebop', 'Cowboy Bebop', 'anime', '/gLh0bH0b6H1q9j1x7w5c3r2m8N.jpg', 1998, ['Animation', 'Sci-Fi', 'Action'], 8.9, 'The crew of the spaceship Bebop hunts bounties across the solar system while outrunning the ghosts of their pasts.', '1 season', ['Kōichi Yamadera', 'Unshō Ishizuka', 'Megumi Hayashibara'], 'Hajime Yatate', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }], { seasons: 1, episodes: 26 }),
  curatedTitle('mob-psycho-100', 'Mob Psycho 100', 'anime', '/oW0Jj1X3V5c7M9n2B4k6L8p0Qz.jpg', 2016, ['Animation', 'Comedy', 'Supernatural'], 8.6, 'A psychic middle school boy tries to live a normal life while keeping his overwhelming powers and emotions in check.', '3 seasons', ['Setsuo Ito', 'Takahiro Sakurai', 'Akio Otsuka'], 'ONE', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }], { seasons: 3, episodes: 37 }),
  curatedTitle('goodfellas', 'Goodfellas', 'movie', '/aKuFiU82s5ISJpGZp7Y4m2L9Q0V.jpg', 1990, ['Crime', 'Drama'], 8.7, 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen and his partners Jimmy and Tommy.', '2h 25m', ['Robert De Niro', 'Ray Liotta', 'Joe Pesci'], 'Martin Scorsese', [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('shawshank-redemption', 'The Shawshank Redemption', 'movie', '/lyQBXzOQSuE59IsHyHRp0qE8J8A.jpg', 1994, ['Drama'], 8.7, 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', '2h 22m', ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'], 'Frank Darabont', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('forrest-gump', 'Forrest Gump', 'movie', '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', 1994, ['Drama', 'Romance'], 8.5, 'The presidencies of Kennedy and Johnson, the Vietnam War, Watergate, and other history unfold through the perspective of an Alabama man with a gentle heart.', '2h 22m', ['Tom Hanks', 'Robin Wright', 'Gary Sinise'], 'Robert Zemeckis', [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Apple TV', kind: 'buy' }]),
  curatedTitle('gladiator', 'Gladiator', 'movie', '/ty8TGRuvJLPUm7WtW2YbV7e7fY.jpg', 2000, ['Action', 'Drama', 'Adventure'], 8.5, 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', '2h 35m', ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'], 'Ridley Scott', [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('fight-club', 'Fight Club', 'movie', '/pB8BM7pdSp6B6Ih7QZ4bJ7a2y4Q.jpg', 1999, ['Drama', 'Thriller'], 8.4, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.', '2h 19m', ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'], 'David Fincher', [{ name: 'Disney+', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('joker', 'Joker', 'movie', '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', 2019, ['Crime', 'Drama', 'Thriller'], 8.2, 'In Gotham City, a failed comedian begins a slow descent into madness as he transforms into a criminal mastermind.', '2h 2m', ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'], 'Todd Phillips', [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('knives-out', 'Knives Out', 'movie', '/pThyQovXQrw2m0s9x82twj1fQX.jpg', 2019, ['Mystery', 'Comedy', 'Crime'], 7.9, 'A detective investigates the death of a patriarch whose dysfunctional family all have something to hide.', '2h 10m', ['Daniel Craig', 'Ana de Armas', 'Chris Evans'], 'Rian Johnson', [{ name: 'Netflix', kind: 'streaming' }]),
  curatedTitle('coco', 'Coco', 'movie', '/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg', 2017, ['Animation', 'Family', 'Fantasy'], 8.4, 'Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather and unlock his family’s musical legacy.', '1h 45m', ['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt'], 'Lee Unkrich', [{ name: 'Disney+', kind: 'streaming' }]),
  curatedTitle('mad-max-fury-road', 'Mad Max: Fury Road', 'movie', '/hA2ple9q4qnwxp3h5tP5M0v1r5H.jpg', 2015, ['Action', 'Adventure', 'Sci-Fi'], 8.1, 'In a ruined wasteland, Max joins Furiosa and a band of rebels fleeing a tyrant in a war rig packed with precious cargo.', '2h 0m', ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'], 'George Miller', [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('the-social-network', 'The Social Network', 'movie', '/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg', 2010, ['Drama', 'History'], 7.8, 'The story of the founders of the social-networking website Facebook and the lawsuits that followed its creation.', '2h 0m', ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'], 'David Fincher', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('the-truman-show', 'The Truman Show', 'movie', '/vuza0WqY239yBXOadKlGwrtu2W.jpg', 1998, ['Comedy', 'Drama', 'Sci-Fi'], 8.2, 'An insurance salesman discovers his whole life is actually a reality TV show created around him.', '1h 43m', ['Jim Carrey', 'Ed Harris', 'Laura Linney'], 'Peter Weir', [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('little-women', 'Little Women', 'movie', '/yn5ihODtZ7ofn8Q5q5h8p0s4c8a.jpg', 2019, ['Drama', 'Romance'], 7.8, 'Four sisters come of age in America in the aftermath of the Civil War.', '2h 15m', ['Saoirse Ronan', 'Emma Watson', 'Florence Pugh'], 'Greta Gerwig', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Apple TV', kind: 'rent' }]),
  curatedTitle('the-wolf-of-wall-street', 'The Wolf of Wall Street', 'movie', '/34m2tygAYBGqA9U3Z2J9x6Yh9sO.jpg', 2013, ['Crime', 'Comedy', 'Drama'], 8.2, 'A wealthy stock-broker leads a life of lavish excess, corruption, and federal investigation on Wall Street.', '3h 0m', ['Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie'], 'Martin Scorsese', [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }]),
  curatedTitle('the-wire', 'The Wire', 'tv', '/4lbclFySvugI51fwsyxBTOm4DqK.jpg', 2002, ['Crime', 'Drama'], 9.3, 'This acclaimed series follows the interconnected lives of Baltimore’s police, dockworkers, politicians, criminals, and journalists.', '5 seasons', ['Dominic West', 'Idris Elba', 'Michael K. Williams'], 'David Simon', [{ name: 'Max', kind: 'streaming' }], { seasons: 5, episodes: 60 }),
  curatedTitle('game-of-thrones', 'Game of Thrones', 'tv', '/1XS1oqL89opfnbLl8WnZY1O1ZPy.jpg', 2011, ['Fantasy', 'Drama', 'Adventure'], 9.2, 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.', '8 seasons', ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'], 'David Benioff', [{ name: 'Max', kind: 'streaming' }], { seasons: 8, episodes: 73 }),
  curatedTitle('black-mirror', 'Black Mirror', 'tv', '/7PRddO7z7mcPi21nYTCMGShAyy1.jpg', 2011, ['Sci-Fi', 'Drama', 'Thriller'], 8.7, 'An anthology series exploring a twisted, high-tech world where humanity’s greatest innovations and darkest instincts collide.', '6 seasons', ['Daniel Lapaine', 'Hannah John-Kamen', 'Michaela Coel'], 'Charlie Brooker', [{ name: 'Netflix', kind: 'streaming' }], { seasons: 6, episodes: 27 }),
  curatedTitle('mr-robot', 'Mr. Robot', 'tv', '/oKIBhzZzDX07SoE2bOL8Y6W5t4M.jpg', 2015, ['Crime', 'Drama', 'Thriller'], 8.5, 'A cybersecurity engineer who suffers from social anxiety is recruited by an underground hacker group to take down corporate America.', '4 seasons', ['Rami Malek', 'Christian Slater', 'Carly Chaikin'], 'Sam Esmail', [{ name: 'Prime Video', kind: 'streaming' }, { name: 'Peacock', kind: 'streaming' }], { seasons: 4, episodes: 45 }),
  curatedTitle('ted-lasso', 'Ted Lasso', 'tv', '/5I3cY4i7x3oW9Q1m5p6u8d2e7a.jpg', 2020, ['Comedy', 'Drama', 'Sport'], 8.8, 'An American football coach is hired to manage a British soccer team, despite having no experience with the sport.', '3 seasons', ['Jason Sudeikis', 'Hannah Waddingham', 'Brett Goldstein'], 'Bill Lawrence', [{ name: 'Apple TV+', kind: 'streaming' }], { seasons: 3, episodes: 34 }),
  curatedTitle('fargo', 'Fargo', 'tv', '/9O1IyJ8g1w5q2r3k6m7n4p0s8t.jpg', 2014, ['Crime', 'Drama', 'Thriller'], 8.8, 'Various chronicles of deception, intrigue, and murder in and around frozen Minnesota, all tied together by a dry sense of humor.', '5 seasons', ['Billy Bob Thornton', 'Martin Freeman', 'Allison Tolman'], 'Noah Hawley', [{ name: 'Hulu', kind: 'streaming' }], { seasons: 5, episodes: 51 }),
  curatedTitle('the-haunting-of-hill-house', 'The Haunting of Hill House', 'tv', '/38P1t6dKcP0w8x3n5r7y1m9q2b.jpg', 2018, ['Horror', 'Drama', 'Mystery'], 8.5, 'A fractured family confronts the haunting memories of their old home and the terrifying events that drove them away.', '1 season', ['Michiel Huisman', 'Carla Gugino', 'Henry Thomas'], 'Mike Flanagan', [{ name: 'Netflix', kind: 'streaming' }], { seasons: 1, episodes: 10 }),
  curatedTitle('the-white-lotus', 'The White Lotus', 'tv', '/5wD2vQ4r7s9p1n3m6k8j0h5g2f.jpg', 2021, ['Comedy', 'Drama'], 8.0, 'The exploits of various guests and employees at an exclusive tropical resort over the span of one week.', '3 seasons', ['Jennifer Coolidge', 'Murray Bartlett', 'Aubrey Plaza'], 'Mike White', [{ name: 'Max', kind: 'streaming' }], { seasons: 3, episodes: 20 }),
  curatedTitle('peaky-blinders', 'Peaky Blinders', 'tv', '/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg', 2013, ['Crime', 'Drama'], 8.6, 'A gangster family epic set in Birmingham, England, in 1919, centered on a boss who returns from the war with a dangerous plan.', '6 seasons', ['Cillian Murphy', 'Helen McCrory', 'Paul Anderson'], 'Steven Knight', [{ name: 'Netflix', kind: 'streaming' }], { seasons: 6, episodes: 36 }),
  curatedTitle('the-last-dance', 'The Last Dance', 'tv', '/fXvKuwr3x5m7n9q1s2d4g6h8j0.jpg', 2020, ['Documentary', 'Sport'], 9.1, 'A chronicle of Michael Jordan and the Chicago Bulls dynasty, featuring unaired footage from the 1997–98 season.', '1 season', ['Michael Jordan', 'Scottie Pippen', 'Dennis Rodman'], 'Jason Hehir', [{ name: 'Netflix', kind: 'streaming' }], { seasons: 1, episodes: 10 }),
  curatedTitle('naruto-shippuden', 'Naruto: Shippuden', 'anime', '/v1V4k4B5Y7C9D2E6F8G0H3J5K1L.jpg', 2007, ['Animation', 'Action', 'Adventure'], 8.7, 'Naruto Uzumaki returns older and stronger to protect his village and rescue his friend from the path of revenge.', '21 seasons', ['Junko Takeuchi', 'Noriaki Sugiyama', 'Chie Nakamura'], 'Masashi Kishimoto', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }], { seasons: 21, episodes: 500 }),
  curatedTitle('dragon-ball-z', 'Dragon Ball Z', 'anime', '/1Y9h8m6k4j2g0f7d5s3a1p8o6n.jpg', 1989, ['Animation', 'Action', 'Adventure'], 8.8, 'Goku and his friends defend Earth from an escalating series of powerful enemies while discovering the limits of their strength.', '9 seasons', ['Masako Nozawa', 'Ryo Horikawa', 'Toshio Furukawa'], 'Akira Toriyama', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }], { seasons: 9, episodes: 291 }),
  curatedTitle('hunter-x-hunter', 'Hunter x Hunter', 'anime', '/6q5pX7r5s3n1m9k8j0h2g4f6d.jpg', 2011, ['Animation', 'Action', 'Adventure'], 9.0, 'Gon Freecss aspires to become a Hunter, a special kind of person who can track down treasures, rare beasts, or other individuals.', '6 seasons', ['Megumi Han', 'Mariya Ise', 'Issei Futamata'], 'Yoshihiro Togashi', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }], { seasons: 6, episodes: 148 }),
  curatedTitle('haikyuu', 'Haikyu!!', 'anime', '/5m3n7q1s9d2f4g6h8j0k2l5p7r.jpg', 2014, ['Animation', 'Comedy', 'Sport'], 8.8, 'A short but passionate volleyball player joins his high school team and learns that winning takes more than natural talent.', '4 seasons', ['Ayumu Murase', 'Kaito Ishikawa', 'Satoshi Hino'], 'Haruichi Furudate', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }], { seasons: 4, episodes: 85 }),
  curatedTitle('jojos-bizarre-adventure', 'JoJo’s Bizarre Adventure', 'anime', '/8j2k4m6n0p1q3r5s7t9v1w3x5y.jpg', 2012, ['Animation', 'Action', 'Fantasy'], 8.5, 'The Joestar family battles supernatural enemies across generations using courage, wit, and extraordinary powers.', '5 seasons', ['Matthew Mercer', 'Daisuke Namikawa', 'Fuminori Komatsu'], 'Hirohiko Araki', [{ name: 'Netflix', kind: 'streaming' }, { name: 'Crunchyroll', kind: 'streaming' }], { seasons: 5, episodes: 190 }),
  curatedTitle('blue-lock', 'Blue Lock', 'anime', '/0n9m7k5j3h1g8f6d4s2a0p8o6i.jpg', 2022, ['Animation', 'Sport', 'Drama'], 8.2, 'A young striker enters an extreme training program designed to create Japan’s next world-class soccer forward.', '2 seasons', ['Kazuki Ura', 'Tasuku Kaito', 'Yūki Ono'], 'Muneyuki Kaneshiro', [{ name: 'Crunchyroll', kind: 'streaming' }], { seasons: 2, episodes: 38 }),
  curatedTitle('frieren-beyond-journeys-end', 'Frieren: Beyond Journey’s End', 'anime', '/4b6d8f0h2j4l6n8p0r2t4v6x8z.jpg', 2023, ['Animation', 'Fantasy', 'Drama'], 9.0, 'After the hero’s party defeats the Demon King, the elven mage Frieren begins a new journey to understand the people she once traveled beside.', '1 season', ['Atsumi Tanezaki', 'Nobuhiko Okamoto', 'Hiroki Tōchi'], 'Kanehito Yamada', [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }], { seasons: 1, episodes: 28 }),
];

export const TITLES: Title[] = [
  { id: 'interstellar', name: 'Interstellar', type: 'movie', poster: img('/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'), backdrop: back('/pbrkL804c8yAv3zBZR4QPEafpAR.jpg'), description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.', releaseYear: 2014, genres: ['Sci-Fi', 'Drama', 'Adventure'], rating: 8.7, runtime: '2h 49m', cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], director: 'Christopher Nolan', providers: [{ name: 'Paramount+', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }, { name: 'Apple TV', kind: 'buy' }] },
  { id: 'dark-knight', name: 'The Dark Knight', type: 'movie', poster: img('/qJ2tW6WMUDux911r6m7haRef0WH.jpg'), backdrop: back('/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg'), description: 'When a menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', releaseYear: 2008, genres: ['Action', 'Crime', 'Drama'], rating: 9.0, runtime: '2h 32m', cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'], director: 'Christopher Nolan', providers: [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }, { name: 'YouTube', kind: 'free' }] },
  { id: 'inception', name: 'Inception', type: 'movie', poster: img('/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg'), backdrop: back('/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg'), description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', releaseYear: 2010, genres: ['Action', 'Sci-Fi', 'Thriller'], rating: 8.8, runtime: '2h 28m', cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'], director: 'Christopher Nolan', providers: [{ name: 'Max', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }, { name: 'Apple TV', kind: 'buy' }] },
  { id: 'spider-verse', name: 'Spider-Man: Across the Spider-Verse', type: 'movie', poster: img('/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg'), backdrop: back('/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg'), description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.', releaseYear: 2023, genres: ['Animation', 'Action', 'Adventure'], rating: 8.6, runtime: '2h 20m', cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'], director: 'Joaquim Dos Santos', providers: [{ name: 'Netflix', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }] },
  { id: 'breaking-bad', name: 'Breaking Bad', type: 'tv', poster: img('/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg'), backdrop: back('/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg'), description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.', releaseYear: 2008, genres: ['Crime', 'Drama', 'Thriller'], rating: 9.5, runtime: '5 seasons', cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'], director: 'Vince Gilligan', seasons: 5, episodes: 62, providers: [{ name: 'Netflix', kind: 'streaming' }, { name: 'AMC+', kind: 'streaming' }] },
  { id: 'stranger-things', name: 'Stranger Things', type: 'tv', poster: img('/49WJfeN0moxb9IPfGn8AIqMGskD.jpg'), backdrop: back('/56v2KjBlU7YIgokJ8I5X5y8n0b2.jpg'), description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.', releaseYear: 2016, genres: ['Drama', 'Fantasy', 'Horror'], rating: 8.6, runtime: '4 seasons', cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'], director: 'The Duffer Brothers', seasons: 4, episodes: 34, providers: [{ name: 'Netflix', kind: 'streaming' }] },
  { id: 'the-last-of-us', name: 'The Last of Us', type: 'tv', poster: img('/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg'), backdrop: back('/9n2tJBplPbgR2Jm3Q1W4lM7pR2a.jpg'), description: 'Twenty years after modern civilization has been destroyed, Joel is tasked with escorting Ellie across a ravaged America.', releaseYear: 2023, genres: ['Drama', 'Action', 'Adventure'], rating: 8.7, runtime: '2 seasons', cast: ['Pedro Pascal', 'Bella Ramsey', 'Anna Torv'], director: 'Craig Mazin', seasons: 2, episodes: 16, providers: [{ name: 'Max', kind: 'streaming' }, { name: 'Prime Video', kind: 'rent' }] },
  { id: 'the-boys', name: 'The Boys', type: 'tv', poster: img('/stTEycfG9928HYGEISBFaG1ngjM.jpg'), backdrop: back('/mGVrXeIjyecj6TKmwPVpRULfX3T.jpg'), description: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.', releaseYear: 2019, genres: ['Action', 'Comedy', 'Crime'], rating: 8.7, runtime: '4 seasons', cast: ['Karl Urban', 'Jack Quaid', 'Antony Starr'], director: 'Eric Kripke', seasons: 4, episodes: 32, providers: [{ name: 'Prime Video', kind: 'streaming' }] },
  { id: 'attack-on-titan', name: 'Attack on Titan', type: 'anime', poster: img('/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg'), backdrop: back('/p1F51Lvj3sMopG3Qm4nU8yV3E7A.jpg'), description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.', releaseYear: 2013, genres: ['Animation', 'Action', 'Fantasy'], rating: 9.1, runtime: '4 seasons', cast: ['Yuki Kaji', 'Yui Ishikawa', 'Marina Inoue'], director: 'Hajime Isayama', seasons: 4, episodes: 89, providers: [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }] },
  { id: 'demon-slayer', name: 'Demon Slayer', type: 'anime', poster: img('/xUfRZu2mi8jH6SzN2M4Lq1d7T6N.jpg'), backdrop: back('/6D2m0f5A3wW2n4Y6v8C1r9B0q7N.jpg'), description: 'A kindhearted boy finds his family slaughtered and his sister turned into a demon. He sets out to find a cure and avenge them.', releaseYear: 2019, genres: ['Animation', 'Action', 'Fantasy'], rating: 8.6, runtime: '4 seasons', cast: ['Natsuki Hanae', 'Akari Kito', 'Hiro Shimono'], director: 'Koyoharu Gotouge', seasons: 4, episodes: 55, providers: [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }] },
  { id: 'jujutsu-kaisen', name: 'Jujutsu Kaisen', type: 'anime', poster: img('/hFWP5HkbVEeG6aF6l8j1nT4cQ7O.jpg'), backdrop: back('/fI8MiZ4e5n2P0r8L6j3K1h7D9Qw.jpg'), description: 'A boy swallows a cursed talisman and becomes host to a powerful curse, joining a secret school of sorcerers.', releaseYear: 2020, genres: ['Animation', 'Action', 'Horror'], rating: 8.8, runtime: '2 seasons', cast: ['Junya Enoki', 'Yuma Uchida', 'Asami Seto'], director: 'Gege Akutami', seasons: 2, episodes: 47, providers: [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }] },
  { id: 'one-piece', name: 'One Piece', type: 'anime', poster: img('/cMD9YgzKihJnyP3WkzJ1n1C6s0R.jpg'), backdrop: back('/i9k1mN2oP3q4R5s6T7u8V9w0X1Y.jpg'), description: 'Monkey D. Luffy and his pirate crew explore the Grand Line in search of the world’s greatest treasure.', releaseYear: 1999, genres: ['Animation', 'Action', 'Adventure'], rating: 8.9, runtime: '21 seasons', cast: ['Mayumi Tanaka', 'Kazuya Nakai', 'Akemi Okamura'], director: 'Eiichiro Oda', seasons: 21, episodes: 1122, providers: [{ name: 'Crunchyroll', kind: 'streaming' }, { name: 'Netflix', kind: 'streaming' }, { name: 'Hulu', kind: 'streaming' }] },
  ...EXPANDED_TITLES,
];

export const INITIAL_USER_TITLES: UserTitle[] = [
  { titleId: 'interstellar', status: 'watched', dateAdded: '2024-01-12', dateWatched: '2024-03-14', rating: 5, review: 'A quiet, enormous film. The organ notes still follow me.', progress: 100 },
  { titleId: 'breaking-bad', status: 'watching', dateAdded: '2024-09-18', currentSeason: 3, currentEpisode: 4, progress: 48 },
  { titleId: 'spider-verse', status: 'watchlist', dateAdded: '2024-10-02' },
  { titleId: 'attack-on-titan', status: 'watching', dateAdded: '2024-08-21', currentSeason: 2, currentEpisode: 7, progress: 31 },
  { titleId: 'dark-knight', status: 'watched', dateAdded: '2023-11-04', dateWatched: '2024-02-03', rating: 5, review: 'The one I return to when I need the lights low.', progress: 100 },
  { titleId: 'the-last-of-us', status: 'watchlist', dateAdded: '2024-10-10' },
];

export const INITIAL_PROFILE: Profile = { username: 'Mara', country: 'United States', appearance: 'night' };
export const titleById = (id: string) => TITLES.find((title) => title.id === id);
export const formatStatus = (status: UserStatus | string | undefined) => status === 'watchlist' ? 'Want to watch' : status === 'watching' ? 'Watching' : 'Watched';